---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/azure-cli

inputs:
  - name: bbr-pipeline-tasks-repo
  - name: om

outputs:
    # Contains exported Ops Manager installation settings in `installation.zip`
  - name: om-installation

run:
  path: bbr-pipeline-tasks-repo/tasks/export-om-installation-to-azure/task.sh

params:
  # The Ops Manager URL, e.g. https://pcf.example.com
  OPSMAN_URL:

  # If true, SSL validation will be skipped when connecting to Ops Manager API
  SKIP_SSL_VALIDATION: false

  # Client credentials for Ops Manager API. If empty, user credentials will be used
  CLIENT_ID:
  CLIENT_SECRET:

  # User credentials for Ops Manager API
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

  # The name of your storage account.
  AZURE_STORAGE_ACCOUNT:

  # The primary or secondary access key for your storage account.
  AZURE_STORAGE_KEY:

  # A name of the container to upload to
  AZURE_STORAGE_CONTAINER:

  # the path to small file on your local computer
  AZURE_STORAGE_VERSIONED_FILE: