---
opsman_credentials: &opsman_credentials
  SKIP_SSL_VALIDATION: ((skip-ssl-validation))
  OPSMAN_URL: ((opsman-url))
  OPSMAN_USERNAME: ((opsman-username))
  OPSMAN_PASSWORD: ((opsman-password))
  OPSMAN_PRIVATE_KEY: ((opsman-private-key))

azure_storage: &azure_storage  
  AZURE_STORAGE_ACCOUNT_NAME: ((azure-storage-account-name))
  AZURE_STORAGE_ACCOUNT_KEY: ((azure-storage-account-key))

resource_types:
# source: https://github.com/pivotal-cf/bosh-creds-resource
- name: bosh-creds
  type: docker-image
  source:
    repository: mkuratczyk/bosh-creds-resource
    tag: 1.4

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:

- name: bbr-pipeline-tasks-repo
  type: git
  source:
    uri: ((bbr_pipelines_repo))
    branch: ((bbr_pipelines_repo_branch))

- name: om
  type: github-release
  source: 
    owner: pivotal-cf
    repository: om

# - name: bosh
#   type: github-release
#   source: 
#     owner: cloudfoundry
#     repository: bosh

#- name: fly
#  type: github-release
#  source: 
#    owner: concourse
#    repository: fly

- name: bbr-release
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: p-bosh-backup-and-restore

jobs:

# keep the backup as a single unit to avoid copying the backup between container volumes
# even resources store a copy so the work must be self contained
- name: bbr-backup-ert-to-azure
  plan:
  - aggregate:
    - get: bbr-release
    - get: bbr-pipeline-tasks-repo
    - get: om
      params:
        globs: 
        - om-linux
  - task: extract-binary
    tags:
    - ((concourse-worker-tag))
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - task: bbr-backup-ert-to-azure
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-ert-to-azure/task.yml
    params:
      <<: *opsman_credentials
      <<: *azure_storage
      AZURE_STORAGE_CONTAINER: ((azure_storage_container_pas_backup))
      AZURE_STORAGE_VERSIONED_FILE: pas-backup.tgz

# keep the backup as a single unit to avoid copying the backup between container volumes
# even resources store a copy so the work must be self contained
- name: bbr-backup-director-to-azure
  plan:
  - aggregate:
    - get: bbr-release
    - get: bbr-pipeline-tasks-repo
    - get: om
      params:
        globs: 
        - om-linux
  - task: extract-binary
    tags:
    - ((concourse-worker-tag))
    file: bbr-pipeline-tasks-repo/tasks/extract-bbr-binary/task.yml
  - task: bbr-backup-director-to-azure
    file: bbr-pipeline-tasks-repo/tasks/bbr-backup-director-to-azure/task.yml
    params:
      <<: *opsman_credentials
      <<: *azure_storage
      AZURE_STORAGE_CONTAINER: ((azure_storage_container_director_backup))
      AZURE_STORAGE_VERSIONED_FILE: director-backup.tgz

# keep the backup as a single unit to avoid copying the backup between container volumes
# even resources store a copy so the work must be self contained
- name: export-om-installation-to-azure
  plan: 
  - aggregate:
    - get: bbr-pipeline-tasks-repo
    - get: om
      params:
        globs:
        - om-linux
  - task: export-om-installation-to-azure
    file: bbr-pipeline-tasks-repo/tasks/export-om-installation-to-azure/task.yml
    params:
      <<: *opsman_credentials
      <<: *azure_storage
      AZURE_STORAGE_CONTAINER: ((azure_storage_container_om_backup))
      AZURE_STORAGE_VERSIONED_FILE: om-installation.zip